on: [push, pull_request]

name: SonarCloud
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get main
      run:  git fetch origin main
    - name: Instalar dependencias
      run:  npm install
    - name: Create env file
      run: |
        touch .env.local
        echo NEXT_PUBLIC_BASE_URL=${{ secrets.ENV_NEXT_PUBLIC_BASE_URL }} >> .env.local
        cat .env.local
    - name: Instalar Jest
      run:  npm install -g jest@28.1.3
    - name: Executar testes
      run:  jest --coverage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
